Step 2
loki1520/frontend-project-12 pull request #2
Opened 2024-09-24 15:57 UTC by loki1520

2024-09-25 06:23 UTC, CoraloReef requested changes

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/App.js
> +      <Route path="login" element={<LoginPage />} />
Я думаю тут нужен абсолютный путь `/login`

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/Components/LoginPage.jsx
> +import { Formik, Form, Field } from 'formik';
Коммент относится к структуре. 

1. Раздел components общепринято писать с маленькой буквы
2. Компоненты страниц принято помещать в папку `pages` (но не настаиваю, могут быть разные подходы)

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/Components/LoginPage.jsx
> +import logo from '../assets/login.png';
Имопрт logo или login?

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/Components/LoginPage.jsx
> +                    {() => (
Не думаю, что здесь jsx нужно оборачивать в функцию

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/Components/LoginPage.jsx
> +                    <span>Нет аккаунта?&nbsp;</span>
Обязательно ли здесь использовать неразрывный пробел?

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/Components/MainPage.jsx
> +          <Link to="*">PageNotFound</Link>
Не нужно делать ссылку на страницу 404 :)

Протестировать работу этой страницы можно написав абракадабру в адресе приложения http://localhost:3000/fsfdgsdfg

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/Components/MainPage.jsx
> +          <Link to="/login">LoginPage</Link>
`<Link to="/login">Авторизация</Link>` ?

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/Components/PageNotFound.jsx
> +const PageNotFound = () => (
Предлагаю назвать в стиле других страниц `NotFoundPage`

2024-09-25 06:23 UTC, CoraloReef commented on frontend/src/Components/PageNotFound.jsx
> +            Но вы можете перейти&nbsp;
Тот же коммент про неразрывный пробел. Если верстка правильная он очень редко нужен. Иначе скорее всего проблема с версткой.

2024-09-25 11:47 UTC, loki1520 commented on frontend/src/App.js
> +      <Route path="login" element={<LoginPage />} />
fixed

2024-09-25 11:49 UTC, loki1520 commented on frontend/src/Components/LoginPage.jsx
> +import { Formik, Form, Field } from 'formik';
Принято, поправил

2024-09-25 11:51 UTC, loki1520 commented on frontend/src/Components/LoginPage.jsx
> +import logo from '../assets/login.png';
исправил на loginImg, это в первую очередь картинка

2024-09-25 11:52 UTC, loki1520 commented on frontend/src/Components/LoginPage.jsx
> +                    {() => (
fixed

2024-09-25 11:56 UTC, loki1520 commented on frontend/src/Components/LoginPage.jsx
> +                    <span>Нет аккаунта?&nbsp;</span>
нет), исправляю

2024-09-25 12:43 UTC, loki1520 commented on frontend/src/Components/MainPage.jsx
> +          <Link to="*">PageNotFound</Link>
это я тестировал link ))
редирект "сделал"

2024-09-25 12:44 UTC, loki1520 commented on frontend/src/Components/MainPage.jsx
> +          <Link to="/login">LoginPage</Link>
убрал этот тест полностью

2024-09-25 12:45 UTC, loki1520 commented on frontend/src/Components/PageNotFound.jsx
> +const PageNotFound = () => (
fixed

2024-09-25 12:45 UTC, loki1520 commented on frontend/src/Components/PageNotFound.jsx
> +            Но вы можете перейти&nbsp;
fixed

2024-09-25 13:21 UTC, CoraloReef commented on frontend/public/index.html
> +<html class="h-100" lang="en">
Не-не, к тегу html классы не добавляем

2024-09-25 13:23 UTC, CoraloReef commented on frontend/public/index.html
> +  <body class="h-100 bg-light">
К body тоже крайне не желательно, лучше внутри Реакт компонента, например Wrapper, сделать блок и на него повесить нужные классы. А с таким подходом ты не сможешь с помощью Реакта переопределить это поведение, если вдруг потребуется

2024-09-25 13:24 UTC, CoraloReef commented on frontend/src/components/pages/LoginPage.jsx
> +import loginImg from '../../assets/login.png';
Так правильно! Сразу понятно, что это картинка и какое ее содержимое.

2024-09-25 13:26 UTC, CoraloReef commented on frontend/src/Components/LoginPage.jsx
> +import { Formik, Form, Field } from 'formik';
Раздел pages обычно выше уровня components. `/src/pages/LoginPage.tsx`

2024-09-25 13:28 UTC, CoraloReef commented on frontend/src/Components/PageNotFound.jsx
> +const PageNotFound = () => (
`notFoundPage` -> `NotFoundPage`

2024-09-25 13:37 UTC, loki1520 commented on frontend/src/Components/PageNotFound.jsx
> +const PageNotFound = () => (
fixed

2024-09-25 14:05 UTC, loki1520 commented on frontend/src/Components/LoginPage.jsx
> +import { Formik, Form, Field } from 'formik';
fixed

2024-09-25 20:56 UTC, loki1520 commented on frontend/public/index.html
> +  <body class="h-100 bg-light">
fix...ed)

2024-09-25 21:04 UTC, loki1520 commented on frontend/public/index.html
> +<html class="h-100" lang="en">
убрал

2024-09-26 05:36 UTC, CoraloReef approved these changes

2024-09-26 09:48 UTC, merged